spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: docker
    schemas: public

